### ISSUE TITLE
Clearing the measure column setting causes the app to fail

### ISSUE THREAD

**Issue by pburnsdata** [SafetyGraphics/safetyGraphics#240]
Deleting the measure column default setting causes the app to crash. It seems related to the fact that it is used in the field level settings.

Get following error:
Warning: Error in hasField: typeof(columnName) == "character" is not TRUE
  71: <Anonymous>

**Comment by jwildfire** [comment]
The `hasField()` check probably shouldn't even be running here since expected behavior should be for the linked `measure_value` options to be cleared when `measure_col` is deleted. Wondering if we lost or broke that observer during the refactor. 

Seems like this only happens when `measure_col` is deleted (not when it is changed), so maybe the issue is just with the edge case where the input is cleared. 

Assigning @bzkrouse to take an initial look.

**Comment by jwildfire** [comment]
Definitely something a bit weird going on. The bug doesn't occur if you change `measure_col` to a different variable before deleting it. There also appears to be a lag in the options for `measure_values`, if you change `measure_col` several times. The screenshot below shows `measure_col` set to `PARAM`, but field options populating from `TRTP`. Odd ...

**Comment by bzkrouse** [comment]
Problematic code that is getting run when measure_col is cleared:
```safetyGraphics:::hasField(fieldValue = "Bilirubin (umol/L)", columnName = NULL, data = adlbc)```
