### ISSUE TITLE
Colorblind friendly palette 

### ISSUE THREAD

**Issue by chasemc** [SafetyGraphics/safetyGraphics#349]
If you aren't restricted, consider using a colorblind friendly plot palette.  Good place to start figuring out what that would be is: 
http://colorbrewer2.org

**Comment by jwildfire** [comment]
We're planning to simplify the app so that the settings page is going to focus only the data mapping. As a result, chart appearance settings (like mark color) will be out of scope for the app after the forthcoming v2.0 release. Like I mentioned above, there still be a way to specify colors on a chart-by-chart basis. That process will be described in a vignette when v2 goes live.
