### ISSUE TITLE
Display chart label (instead of chart name) on HTML report

### ISSUE THREAD

**Issue by bzkrouse** [SafetyGraphics/safetyGraphics#392]
Current version displays the chart name (e.g. deltadelta) rather than the label (Delta-Delta)

**Comment by jwildfire** [comment]
Check to make sure this is fixed in v2.0 reports tab

**Comment by pburnsdata** [comment]
assigning this for me to do post thanksgiving as some level of attempting to be involved. if you need it sooner feel free to take it back

**Comment by jwildfire** [comment]
@pburnsdata that would be great! I'd hold off on coding here for now, since the reporting process is going to be rewritten to some degree in v2, but we haven't started development just yet - would be great to have your help there though, since you wrote so much of the original. 

I'd suggest taking a look at #440 and the associated vignette draft to get familiar with the revised charting workflow, and then we can chat, and figure out the best way to tackle this.

**Comment by jwildfire** [comment]
@pburnsdata I'm actually just going to close this in favor of the more general issue I just filed #449. Let's chat about that soon.
